# Data Wrangling
## Imports

In [1]:
import pandas as pd
import numpy as np
import requests
import os

## Gather
The original data set csv file can be found at [this link](https://s3.amazonaws.com/udacity-hosted-downloads/ud651/prosperLoanData.csv).

In [2]:
prosper_loan_data_url = 'https://s3.amazonaws.com/udacity-hosted-downloads/ud651/prosperLoanData.csv'
file_name = prosper_loan_data_url.split('/')[-1]

if not os.path.isfile(file_name):
    # Retrieve the file content from the web
    response = requests.get(prosper_loan_data_url)
    # And save it in a tsv file
    with open(file_name, mode='wb') as file:
        file.write(response.content)
        
# Create propser loan DataFrame from the downloaded csv file
df_loan_data = pd.read_csv(file_name)
df_loan_data.head()

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,C,36,Completed,2009-08-14 00:00:00,0.16516,0.1580,0.1380,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.0920,0.0820,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,81716,2007-01-05 15:00:47.090000000,HR,36,Completed,2009-12-17 00:00:00,0.28269,0.2750,0.2400,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,NaN,36,Current,NaN,0.12528,0.0974,0.0874,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,NaN,36,Current,NaN,0.24614,0.2085,0.1985,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20

In [3]:
df_loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  object
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   object
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  object
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  object
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  object
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.1+ MB

## Variables usefulness assessment
In this first asses part, I will define which variable I want to keep for the data analysis and visualisation part that I will perform for this project.

In [4]:
pd.set_option('display.max_rows', 85)
pd.set_option('display.max_colwidth', 200)
df_loan_data_variable_def = pd.read_csv('ProsperLoanData_VariableDefiefinition.csv', index_col='Variable')
df_loan_data_variable_def

                                                                                                                                                                                                                                 Description
Variable
ListingKey                                                                                                                                       Unique key for each listing, same value as the 'key' used in the listing object in the API.
ListingNumber                                                                                                                                     The number that uniquely identifies the listing to the public as displayed on the website.
ListingCreationDate                                                                                                                                                                                        The date the listing was created.
CreditGrade                                                                    The Credit rating that was assigned at the time the listing went live. Applicable for listings pre-2009 period and will only be populated for those listings.
Term                                                                                                                                                                                             The length of the loan expressed in months.
LoanStatus                                           The current status of the loan: Cancelled,  Chargedoff, Completed, Current, Defaulted, FinalPaymentInProgress, PastDue. The PastDue status will be accompanied by a delinquency bucket.
ClosedDate                                                                                                                                      Closed date is applicable for Cancelled, Completed, Chargedoff and Defaulted loan statuses.
BorrowerAPR                                                                                                                                                                        The Borrower's Annual Percentage Rate (APR) for the loan.
BorrowerRate                                                                                                                                                                                    The Borrower's interest rate for this loan.
LenderYield                                                                                                                     The Lender yield on the loan. Lender yield is equal to the interest rate on the loan less the servicing fee.
EstimatedEffectiveYield              Effective yield is equal to the borrower interest rate (i) minus the servicing fee rate, (ii) minus estimated uncollected interest on charge-offs, (iii) plus estimated collected late fees.  Applic...
EstimatedLoss                                                                                                                Estimated loss is the estimated principal loss on charge-offs. Applicable for loans originated after July 2009.
EstimatedReturn                      The estimated return assigned to the listing at the time it was created. Estimated return is the difference between the Estimated Effective Yield and the Estimated Loss Rate. Applicable for loans ...
ProsperRating (numeric)                                      The  Prosper Rating assigned at the time the listing was created: 0 - N/A, 1 - HR, 2 - E, 3 - D, 4 - C, 5 - B, 6 - A, 7 - AA.  Applicable for loans originated after July 2009.
ProsperRating (Alpha)                                                                                     The Prosper Rating assigned at the time the listing was created between AA - HR.  Applicable for loans originated after July 2009.
ProsperScore                                            A custom risk score built using historical Prosper data. The score ranges from 1-10, with 10 being the best, or lowest risk score.  Applicable for loans originated after July 2009.
ListingCategory                      The category of the listing that the borrower selected when posting their listing: 0 - Not Available, 1 - Debt Consolidation, 2 - Home Improvement, 3 - Business, 4 - Personal Loan, 5 - Student Use...
BorrowerState                                                                                                                   The two letter abbreviation of the state of the address of the borrower at the time the Listing was created.
Occupation                                                                                                                                                     The Occupation selected by the Borrower at the time they created the listing.
EmploymentStatus                                                                                                                                                  The employment status of the borrower at the time they posted the listing.
EmploymentStatusDuration                                                                                                                                  The length in months of the employment status at the time the listing was created.
IsBorrowerHomeowner                                                                    A Borrower will be classified as a homowner if they have a mortgage on their credit profile or provide documentation confirming they are a homeowner.
CurrentlyInGroup                                                                                                                                   Specifies whether or not the Borrower was in a group at the time the listing was created.
GroupKey                                                                                                    The Key of the group in which the Borrower is a member of. Value will be null if the borrower does not have a group affiliation.
DateCreditPulled                                                                                                                                                                                    The date the credit profile was pulled.
CreditScoreRangeLower                                                                                                  The lower value representing the range of the borrower's credit score as provided by a consumer credit rating agency.
CreditScoreRangeUpper                                                                                                 The upper value representing the range of the borrower's credit score as provided by a consumer credit rating agency.
FirstRecordedCreditLine                                                                                                                                                                           The date the first credit line was opened.
CurrentCreditLines                                                                                                                                                 Number of current credit lines at the time the credit profile was pulled.
OpenCreditLines                                                                                                                                                       Number of open credit lines at the time the credit profile was pulled.
TotalCreditLinespast7years                                                                                                                         Number of credit lines in the past seven years at the time the credit profile was pulled.
OpenRevolvingAccounts                                                                                                                                           Number of open revolving accounts at the time the credit profile was pulled.
OpenRevolvingMonthlyPayment                                                                                                                                 Monthly payment on revolving accounts at the time the credit profile was pulled.
InquiriesLast6Months                                                                                                                                   Number of inquiries in the past six months at the time the credit profile was pulled.
TotalInquiries                                                                                                                                                          Total number of inquiries at the time the credit profile was pulled.
CurrentDelinquencies                                                                                                                                                Number of accounts delinquent at the time the credit profile was pulled.
AmountDelinquent                                                                                                                                                               Dollars delinquent at the time the credit profile was pulled.
DelinquenciesLast7Years                                                                                                                               Number of delinquencies in the past 7 years at the time the credit profile was pulled.
PublicRecordsLast10Years                                                                                                                            Number of public records in the past 10 years at the time the credit profile was pulled.
PublicRecordsLast12Months                                                                                                                          Number of public records in the past 12 months at the time the credit profile was pulled.
RevolvingCreditBalance                                                                                                                                                Dollars of revolving credit at the time the credit profile was pulled.
BankcardUtilization                                                                                                                 The percentage of available revolving credit that is utilized at the time the credit profile was pulled.
AvailableBankcardCredit                                                                                                                                  The total available credit via bank card at the time the credit profile was pulled.
TotalTrades                                                                                                                                                     Number of trade lines ever opened at the time the credit profile was pulled.
TradesNeverDelinquent                                                                                                                            Number of trades that have never been delinquent at the time the credit profile was pulled.
TradesOpenedLast6Months                                                                                                                              Number of trades opened in the last 6 months at the time the credit profile was pulled.
DebtToIncomeRatio                    The debt to income ratio of the borrower at the time the credit profile was pulled. This value is Null if the debt to income ratio is not available. This value is capped at 10.01 (any debt to inco...
IncomeRange                                                                                                                                                            The income range of the borrower at the time the listing was created.
IncomeVerifiable                                                                                                                                        The borrower indicated they have the required documentation to support their income.
StatedMonthlyIncome                                                                                                                                              The monthly income the borrower stated at the time the listing was created.
LoanKey                                                                                                                                                             Unique key for each loan. This is the same key that is used in the API.
TotalProsperLoans                                                                                   Number of Prosper loans the borrower at the time they created this listing. This value will be null if the borrower had no prior loans.
TotalProsperPaymentsBilled                                                  Number of on time payments the borrower made on Prosper loans at the time they created this listing. This value will be null if the borrower had no prior loans.
OnTimeProsperPayments                                                   Number of on time payments the borrower had made on Prosper loans at the time they created this listing. This value will be null if the borrower has no prior loans.
ProsperPaymentsLessThanOneMonthLate             Number of payments the borrower made on Prosper loans that were less than one month late at the time they created this listing. This value will be null if the borrower had no prior loans.
ProsperPaymentsOneMonthPlusLate               Number of payments the borrower made on Prosper loans that were greater than one month late at the time they created this listing. This value will be null if the borrower had no prior loans.
ProsperPrincipalBorrowed                                                                          Total principal borrowed on Prosper loans at the time the listing was created. This value will be null if the borrower had no prior loans.
ProsperPrincipalOutstanding                                                                          Principal outstanding on Prosper loans at the time the listing was created. This value will be null if the borrower had no prior loans.
ScorexChangeAtTimeOfListing          Borrower's credit score change at the time the credit profile was pulled. This will be the change relative to the borrower's last Prosper loan. This value will be null if the borrower had no prior...
LoanCurrentDaysDelinquent                                                                                                                                                                                    The number of days delinquent.
LoanFirstDefaultedCycleNumber                                                                                                                   The cycle the loan was charged off. If the loan has not charged off the value will be null.
LoanMonthsSinceOrigination                                                                                                                                                                       Number of months since the loan originated.
LoanNumber                                                                                                                                                                                    Unique numeric value associated with the loan.
LoanOriginalAmount                                                                                                                                                                                       The origination amount of the loan.
LoanOriginationDate                                                                                                                                                                                        The date the loan was originated.
LoanOriginationQuarter                                                                                                                                                                         The quarter in which the loan was originated.
MemberKey                                                                                                           The unique key that is associated with the borrower. This is the same identifier that is used in the API member object.
MonthlyLoanPayment                                                                                                                                                                                       The scheduled monthly loan payment.
LP_CustomerPayments                                                                          Pre charge-off cumulative gross payments made by the borrower on the loan. If the loan has charged off, this value will exclude any recoveries.
LP_CustomerPrincipalPayments                                                             Pre charge-off cumulative principal payments made by the borrower on the loan. If the loan has charged off, this value will exclude any recoveries.
LP_InterestandFees                                                                                    Pre charge-off cumulative interest and fees paid by the borrower. If the loan has charged off, this value will exclude any recoveries.
LP_ServiceFees                                                                                                                                                 Cumulative service fees paid by the investors who have invested in the loan.
LP_CollectionFees                                                                                                                                            Cumulative collection fees paid by the investors who have invested in the loan.
LP_GrossPrincipalLoss                                                                                                                                                                              The gross charged off amount of the loan.
LP_NetPrincipalLoss                                                                                                                                                             The principal that remains uncollected after any recoveries.
LP_NonPrincipalRecoverypayments                                                      The interest and fee component of any recovery payments. The current payment policy applies payments in the following order: Fees, interest, principal.
PercentFunded                                                                                                                                                                                                Percent the listing was funded.
Recommendations                                                                                                                                              Number of recommendations the borrower had at the time the listing was created.
InvestmentFromFriendsCount                                                                                                                                                            Number of friends that made an investment in the loan.
InvestmentFromFriendsAmount                                                                                                                                                          Dollar amount of investments that were made by friends.
Investors                                                                                                                                                                                      The number of investors that funded the loan.

In [5]:
pd.reset_option("display.max_rows")
pd.reset_option("display.max_colwidth")

Here is the list of variables I wish to keep for my analysis:
- LoanStatus: The current status of the loan: Cancelled,  Chargedoff, Completed, Current, Defaulted, FinalPaymentInProgress, PastDue. The PastDue status will be accompanied by a delinquency bucket.
- BorrowerRate: The Borrower's interest rate for this loan. 
- ListingCategory: The category of the listing that the borrower selected when posting their listing: 0 - Not Available, 1 - Debt Consolidation, 2 - Home Improvement, 3 - Business, 4 - Personal Loan, 5 - Student Use, 6 - Auto, 7- Other, 8 - Baby&Adoption, 9 - Boat, 10 - Cosmetic Procedure, 11 - Engagement Ring, 12 - Green Loans, 13 - Household Expenses, 14 - Large Purchases, 15 - Medical/Dental, 16 - Motorcycle, 17 - RV, 18 - Taxes, 19 - Vacation, 20 - Wedding Loans
- Occupation: The Occupation selected by the Borrower at the time they created the listing.
- IsBorrowerHomeowner: A Borrower will be classified as a homowner if they have a mortgage on their credit profile or provide documentation confirming they are a homeowner.
- CreditScoreRangeLower: The lower value representing the range of the borrower's credit score as provided by a consumer credit rating agency.
- CreditScoreRangeUpper: The upper value representing the range of the borrower's credit score as provided by a consumer credit rating agency. 
- DelinquenciesLast7Years: Number of delinquencies in the past 7 years at the time the credit profile was pulled.
- LoanOriginalAmount: The origination amount of the loan.
- LoanOriginationDate: The date the loan was originated.
- Recommendations: Number of recommendations the borrower had at the time the listing was created.

In [6]:
variables_to_analyze = ['LoanStatus',
                        'BorrowerRate',
                        'ListingCategory (numeric)',
                        'Occupation',
                        'IsBorrowerHomeowner',
                        'CreditScoreRangeLower',
                        'CreditScoreRangeUpper',
                        'DelinquenciesLast7Years',
                        'StatedMonthlyIncome',
                        'LoanOriginalAmount',
                        'LoanOriginationDate',
                        'Recommendations']

In [7]:
df_loan_data_cleaned = df_loan_data[variables_to_analyze]
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 12 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   LoanStatus                 113937 non-null  object
 1   BorrowerRate               113937 non-null  float64
 2   ListingCategory (numeric)  113937 non-null  int64
 3   Occupation                 110349 non-null  object
 4   IsBorrowerHomeowner        113937 non-null  bool
 5   CreditScoreRangeLower      113346 non-null  float64
 6   CreditScoreRangeUpper      113346 non-null  float64
 7   DelinquenciesLast7Years    112947 non-null  float64
 8   StatedMonthlyIncome        113937 non-null  float64
 9   LoanOriginalAmount         113937 non-null  int64
 10  LoanOriginationDate        113937 non-null  object
 11  Recommendations            113937 non-null  int64
dtypes: bool(1), float64(5), int64(3), object(3)
memory usage: 9.7+ MB

In [8]:
df_loan_data_cleaned.describe()

,BorrowerRate,ListingCategory (numeric),CreditScoreRangeLower,CreditScoreRangeUpper,DelinquenciesLast7Years,StatedMonthlyIncome,LoanOriginalAmount,Recommendations
count,113937.000000,113937.000000,113346.000000,113346.000000,112947.000000,1.139370e+05,113937.00000,113937.000000
mean,0.192764,2.774209,685.567731,704.567731,4.154984,5.608026e+03,8337.01385,0.048027
std,0.074818,3.996797,66.458275,66.458275,10.160216,7.478497e+03,6245.80058,0.332353
min,0.000000,0.000000,0.000000,19.000000,0.000000,0.000000e+00,1000.00000,0.000000
25%,0.134000,1.000000,660.000000,679.000000,0.000000,3.200333e+03,4000.00000,0.000000
50%,0.184000,1.000000,680.000000,699.000000,0.000000,4.666667e+03,6500.00000,0.000000
75%,0.250000,3.000000,720.000000,739.000000,3.000000,6.825000e+03,12000.00000,0.000000
max,0.497500,20.000000,880.000000,899.000000,99.000000,1.750003e+06,35000.00000,39.000000

# Data quality and tidyness assessment
Here is the list of issues in the dataset that need to be solved before performing any analysis:
- CreditScoreRangeLower and CreditScoreRangeUpper could be merged into one average variable
- Some variables have missing values
  - Occupation
  - CreditScoreRangeLower
  - CreditScoreRangeUpper
  - DelinquenciesLast7Years
- Some variables don't have the right type:
  - LoanStatus should be a category instead of an object
  - ListingCategory should be a category instead of an int
  - Occupation should be a category instead of an object
  - DelinquenciesLast7Years should be a int instead of a float
  - LoanOriginationDate should be a date instead of an object
  
# Data cleaning
## CreditScoreRangeLower and CreditScoreRangeUpper
### Assess, Define and code

In [9]:
df_loan_data_cleaned[df_loan_data_cleaned.CreditScoreRangeLower.isna() | df_loan_data_cleaned.CreditScoreRangeUpper.isna()]

,LoanStatus,BorrowerRate,ListingCategory (numeric),Occupation,IsBorrowerHomeowner,CreditScoreRangeLower,CreditScoreRangeUpper,DelinquenciesLast7Years,StatedMonthlyIncome,LoanOriginalAmount,LoanOriginationDate,Recommendations
206,Defaulted,0.2700,0,NaN,False,NaN,NaN,NaN,9166.666667,7500,2006-03-29 00:00:00,0
387,Completed,0.0865,0,NaN,False,NaN,NaN,NaN,3000.000000,3500,2006-03-13 00:00:00,0
698,Completed,0.0700,0,NaN,False,NaN,NaN,NaN,8333.333333,6001,2006-02-09 00:00:00,0
1023,Completed,0.0800,0,NaN,False,NaN,NaN,NaN,8333.333333,5000,2006-04-05 00:00:00,0
1126,Completed,0.2000,0,NaN,False,NaN,NaN,NaN,4250.000000,2550,2006-03-15 00:00:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...
112680,Chargedoff,0.1375,0,NaN,False,NaN,NaN,NaN,3000.000000,7000,2006-02-22 00:00:00,0
113015,Completed,0.1200,0,NaN,False,NaN,NaN,NaN,3250.000000,5000,2006-04-17 00:00:00,0
113438,Completed,0.0800,0,NaN,False,NaN,NaN,NaN,5833.333333,3000,2006-03-02 00:00:00,0
113902,Completed,0.0812,0,NaN,False,NaN,NaN,NaN,20833.333333,7500,2006-04-04 00:00:00,0
113921,Completed,0.0400,0,NaN,False,NaN,NaN,NaN,12500.000000,1000,2005-11-15 00:00:00,0

Since there is no way to guess the borrower credit score and that it seems that the entries which have NaN in CreditScoreRangeLower and CreditScoreRangeUpper also have NaN in a lot of other variables, I will remove the rows where there is NaN in CreditScoreRangeLower or CreditScoreRangeUpper.

In [10]:
df_loan_data_cleaned = df_loan_data_cleaned[~df_loan_data_cleaned.CreditScoreRangeLower.isna() | ~df_loan_data_cleaned.CreditScoreRangeUpper.isna()]
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113346 entries, 0 to 113936
Data columns (total 12 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   LoanStatus                 113346 non-null  object
 1   BorrowerRate               113346 non-null  float64
 2   ListingCategory (numeric)  113346 non-null  int64
 3   Occupation                 110347 non-null  object
 4   IsBorrowerHomeowner        113346 non-null  bool
 5   CreditScoreRangeLower      113346 non-null  float64
 6   CreditScoreRangeUpper      113346 non-null  float64
 7   DelinquenciesLast7Years    112947 non-null  float64
 8   StatedMonthlyIncome        113346 non-null  float64
 9   LoanOriginalAmount         113346 non-null  int64
 10  LoanOriginationDate        113346 non-null  object
 11  Recommendations            113346 non-null  int64
dtypes: bool(1), float64(5), int64(3), object(3)
memory usage: 10.5+ MB

In [11]:
df_loan_data_cleaned['CreditScoreRangeAvg'] = (df_loan_data_cleaned.CreditScoreRangeLower + df_loan_data_cleaned.CreditScoreRangeUpper) / 2

In order to have only one variable representing the score of the borrower, I will transform the CreditScoreRangeLower and CreditScoreRangeUpper into the credit score range average.

In [12]:
df_loan_data_cleaned.drop(columns=['CreditScoreRangeLower', 'CreditScoreRangeUpper'], inplace=True)

### Test

In [13]:
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113346 entries, 0 to 113936
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   LoanStatus                 113346 non-null  object
 1   BorrowerRate               113346 non-null  float64
 2   ListingCategory (numeric)  113346 non-null  int64
 3   Occupation                 110347 non-null  object
 4   IsBorrowerHomeowner        113346 non-null  bool
 5   DelinquenciesLast7Years    112947 non-null  float64
 6   StatedMonthlyIncome        113346 non-null  float64
 7   LoanOriginalAmount         113346 non-null  int64
 8   LoanOriginationDate        113346 non-null  object
 9   Recommendations            113346 non-null  int64
 10  CreditScoreRangeAvg        113346 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(3)
memory usage: 9.6+ MB

In [14]:
df_loan_data_cleaned.CreditScoreRangeAvg.describe()

count    113346.000000
mean        695.067731
std          66.458275
min           9.500000
25%         669.500000
50%         689.500000
75%         729.500000
max         889.500000
Name: CreditScoreRangeAvg, dtype: float64

## Occupation
### Assess, define and code

In [15]:
df_loan_data_cleaned.Occupation.value_counts()

Other                          28616
Professional                   13628
Computer Programmer             4478
Executive                       4311
Teacher                         3759
                               ...
Dentist                           68
Student - College Freshman        41
Student - Community College       28
Judge                             22
Student - Technical School        16
Name: Occupation, Length: 67, dtype: int64

In [16]:
df_loan_data_cleaned[df_loan_data_cleaned.Occupation.isna()]

,LoanStatus,BorrowerRate,ListingCategory (numeric),Occupation,IsBorrowerHomeowner,DelinquenciesLast7Years,StatedMonthlyIncome,LoanOriginalAmount,LoanOriginationDate,Recommendations,CreditScoreRangeAvg
34,Current,0.1920,1,NaN,True,15.0,4058.333333,10000,2014-02-27 00:00:00,0,649.5
39,Completed,0.1450,0,NaN,False,0.0,9583.333333,10000,2006-07-17 00:00:00,0,689.5
92,Completed,0.0755,0,NaN,True,0.0,10833.333333,2300,2006-07-11 00:00:00,0,829.5
146,Completed,0.0925,0,NaN,False,0.0,0.083333,4000,2006-08-29 00:00:00,0,749.5
161,Current,0.1355,1,NaN,True,33.0,2429.166667,4000,2013-12-26 00:00:00,0,689.5
...,...,...,...,...,...,...,...,...,...,...,...
113651,Past Due (1-15 days),0.1550,19,NaN,False,0.0,1666.666667,2500,2013-09-30 00:00:00,0,749.5
113663,Chargedoff,0.2875,0,NaN,False,8.0,3500.000000,2500,2006-07-05 00:00:00,0,529.5
113709,Current,0.2925,1,NaN,False,52.0,4000.000000,4000,2013-12-10 00:00:00,0,649.5
113712,Defaulted,0.2375,0,NaN,False,0.0,7500.000000,6001,2006-06-15 00:00:00,0,509.5
113914,Defaulted,0.2500,0,NaN,False,16.0,2400.000000,3000,2006-08-18 00:00:00,0,529.5

Since this is impossible to guess the Occupation of a borrower, I will remove the entries with NaN in Occupation.

In [17]:
df_loan_data_cleaned.dropna(subset=['Occupation'], inplace=True)
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110347 entries, 0 to 113936
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   LoanStatus                 110347 non-null  object
 1   BorrowerRate               110347 non-null  float64
 2   ListingCategory (numeric)  110347 non-null  int64
 3   Occupation                 110347 non-null  object
 4   IsBorrowerHomeowner        110347 non-null  bool
 5   DelinquenciesLast7Years    110261 non-null  float64
 6   StatedMonthlyIncome        110347 non-null  float64
 7   LoanOriginalAmount         110347 non-null  int64
 8   LoanOriginationDate        110347 non-null  object
 9   Recommendations            110347 non-null  int64
 10  CreditScoreRangeAvg        110347 non-null  float64
dtypes: bool(1), float64(4), int64(3), object(3)
memory usage: 9.4+ MB

Now that we don't have any NaN left, I will update the category of Occupation
Since Occupation has a limited amount of unique values which are non ordinal, I will simply transform it into category.

In [18]:
df_loan_data_cleaned.Occupation = df_loan_data_cleaned.Occupation.astype('category')

### Test

In [19]:
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110347 entries, 0 to 113936
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   LoanStatus                 110347 non-null  object
 1   BorrowerRate               110347 non-null  float64
 2   ListingCategory (numeric)  110347 non-null  int64
 3   Occupation                 110347 non-null  category
 4   IsBorrowerHomeowner        110347 non-null  bool
 5   DelinquenciesLast7Years    110261 non-null  float64
 6   StatedMonthlyIncome        110347 non-null  float64
 7   LoanOriginalAmount         110347 non-null  int64
 8   LoanOriginationDate        110347 non-null  object
 9   Recommendations            110347 non-null  int64
 10  CreditScoreRangeAvg        110347 non-null  float64
dtypes: bool(1), category(1), float64(4), int64(3), object(2)
memory usage: 8.6+ MB

## DelinquenciesLast7Years
### Assess, define and code

In [20]:
df_loan_data_cleaned[df_loan_data_cleaned.DelinquenciesLast7Years.isna()]

,LoanStatus,BorrowerRate,ListingCategory (numeric),Occupation,IsBorrowerHomeowner,DelinquenciesLast7Years,StatedMonthlyIncome,LoanOriginalAmount,LoanOriginationDate,Recommendations,CreditScoreRangeAvg
794,Completed,0.2900,0,Other,False,NaN,115.583333,4000,2007-02-22 00:00:00,0,9.5
802,Defaulted,0.2900,0,Student - Technical School,False,NaN,960.000000,2500,2006-10-26 00:00:00,0,629.5
1685,Chargedoff,0.1625,0,Other,False,NaN,1600.000000,1000,2007-02-21 00:00:00,0,9.5
4430,Defaulted,0.1450,0,Sales - Commission,False,NaN,166.666667,1000,2006-10-03 00:00:00,0,9.5
6877,Chargedoff,0.0700,0,Administrative Assistant,False,NaN,2227.500000,1000,2007-02-13 00:00:00,0,9.5
...,...,...,...,...,...,...,...,...,...,...,...
109468,Completed,0.1200,0,Homemaker,False,NaN,0.083333,2550,2007-02-16 00:00:00,0,9.5
109471,Completed,0.1820,6,Other,False,NaN,2091.166667,1300,2008-02-19 00:00:00,0,629.5
109522,Chargedoff,0.2000,0,Student - College Junior,False,NaN,1708.333333,1200,2006-11-30 00:00:00,0,9.5
111624,Defaulted,0.2900,0,Laborer,False,NaN,2333.333333,3002,2007-01-23 00:00:00,0,9.5
113848,Completed,0.2875,0,Administrative Assistant,False,NaN,833.333333,1000,2007-02-13 00:00:00,0,9.5

In [21]:
df_loan_data_cleaned.DelinquenciesLast7Years.describe()

count    110261.000000
mean          4.093134
std          10.056597
min           0.000000
25%           0.000000
50%           0.000000
75%           3.000000
max          99.000000
Name: DelinquenciesLast7Years, dtype: float64

Since most of the borrowers have 0 delinquency in the last 7 years and that I don't observe any pattern in the entries where DelinquenciesLast7Years is NaN, I will replace the NaN in DelinquenciesLast7Years with 0.

In [22]:
df_loan_data_cleaned.DelinquenciesLast7Years.fillna(0, inplace=True)
df_loan_data_cleaned.DelinquenciesLast7Years = df_loan_data_cleaned.DelinquenciesLast7Years.astype(int)

### Test

In [23]:
df_loan_data_cleaned.DelinquenciesLast7Years.describe()

count    110347.000000
mean          4.089944
std          10.053326
min           0.000000
25%           0.000000
50%           0.000000
75%           3.000000
max          99.000000
Name: DelinquenciesLast7Years, dtype: float64

In [24]:
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110347 entries, 0 to 113936
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   LoanStatus                 110347 non-null  object
 1   BorrowerRate               110347 non-null  float64
 2   ListingCategory (numeric)  110347 non-null  int64
 3   Occupation                 110347 non-null  category
 4   IsBorrowerHomeowner        110347 non-null  bool
 5   DelinquenciesLast7Years    110347 non-null  int64
 6   StatedMonthlyIncome        110347 non-null  float64
 7   LoanOriginalAmount         110347 non-null  int64
 8   LoanOriginationDate        110347 non-null  object
 9   Recommendations            110347 non-null  int64
 10  CreditScoreRangeAvg        110347 non-null  float64
dtypes: bool(1), category(1), float64(3), int64(4), object(2)
memory usage: 8.6+ MB

We can now notice that we don't have any NaN anymore in the data set

## LoanStatus
### Assess, define and code

In [25]:
df_loan_data_cleaned.LoanStatus.value_counts()

Current                   55272
Completed                 36620
Chargedoff                11701
Defaulted                  4496
Past Due (1-15 days)        798
Past Due (31-60 days)       358
Past Due (61-90 days)       313
Past Due (91-120 days)      304
Past Due (16-30 days)       264
FinalPaymentInProgress      203
Past Due (>120 days)         16
Cancelled                     2
Name: LoanStatus, dtype: int64

The loan statuses can be seen as an ordinal variable because some status are better than other. I will then transform the variable from object to ordered category.

Since Cancelled status concerns only one loan, I will get ride of the entry

In [26]:
df_loan_data_cleaned = df_loan_data_cleaned[df_loan_data_cleaned.LoanStatus != 'Cancelled']
df_loan_data_cleaned.LoanStatus.value_counts()

Current                   55272
Completed                 36620
Chargedoff                11701
Defaulted                  4496
Past Due (1-15 days)        798
Past Due (31-60 days)       358
Past Due (61-90 days)       313
Past Due (91-120 days)      304
Past Due (16-30 days)       264
FinalPaymentInProgress      203
Past Due (>120 days)         16
Name: LoanStatus, dtype: int64

Let's now transform the variable from string to an ordered category.

In [27]:
loan_status_list = ['Chargedoff',
                    'Defaulted',
                    'Past Due (>120 days)',
                    'Past Due (91-120 days)',
                    'Past Due (61-90 days)',
                    'Past Due (31-60 days)',
                    'Past Due (16-30 days)',
                    'Past Due (1-15 days)',
                    'Current',
                    'FinalPaymentInProgress',
                    'Completed',]
loan_status_class = pd.api.types.CategoricalDtype(ordered=True, categories=loan_status_list)
df_loan_data_cleaned.LoanStatus = df_loan_data_cleaned.LoanStatus.astype(loan_status_class);

### Test

In [28]:
df_loan_data_cleaned.LoanStatus

0                      Completed
1                        Current
2                      Completed
3                        Current
4                        Current
                   ...
113932                   Current
113933    FinalPaymentInProgress
113934                   Current
113935                 Completed
113936                   Current
Name: LoanStatus, Length: 110345, dtype: category
Categories (11, object): ['Chargedoff' < 'Defaulted' < 'Past Due (>120 days)' < 'Past Due (91-120 days)' ... 'Past Due (1-15 days)' < 'Current' < 'FinalPaymentInProgress' < 'Completed']

## ListingCategory
### Assess, define and code

In [29]:
df_loan_data_cleaned['ListingCategory (numeric)'].value_counts()

1     57198
0     14707
7     10399
2      7392
3      7184
6      2562
4      2395
13     1975
15     1500
18      880
14      865
20      769
19      758
5       756
16      304
11      217
8       199
10       91
9        85
12       58
17       51
Name: ListingCategory (numeric), dtype: int64

Each number correspond to a reason for the loan. The matching categories are given in the variable description.

The category of the listing that the borrower selected when posting their listing: 
- 0 - Not Available,
- 1 - Debt Consolidation,
- 2 - Home Improvement,
- 3 - Business,
- 4 - Personal Loan,
- 5 - Student Use,
- 6 - Auto,
- 7 - Other,
- 8 - Baby&Adoption,
- 9 - Boat,
- 10 - Cosmetic Procedure,
- 11 - Engagement Ring,
- 12 - Green Loans,
- 13 - Household Expenses,
- 14 - Large Purchases,
- 15 - Medical/Dental,
- 16 - Motorcycle,
- 17 - RV,
- 18 - Taxes,
- 19 - Vacation,
- 20 - Wedding Loans

Since the category are not ordered, I will transform the numeric listing into a string listing and then transform it into a simple category variable.

In [30]:
listing_num_to_string = {
    0: 'Not Available',
    1: 'Debt Consolidation',
    2: 'Home Improvement',
    3: 'Business',
    4: 'Personal Loan',
    5: 'Student Use',
    6: 'Auto',
    7: 'Other',
    8: 'Baby Adoption',
    9: 'Boat',
    10: 'Cosmetic Procedure',
    11: 'Engagement Ring',
    12: 'Green Loans',
    13: 'Household Expenses',
    14: 'Large Purchases',
    15: 'Medical/Dental',
    16: 'Motorcycle',
    17: 'RV',
    18: 'Taxes',
    19: 'Vacation',
    20: 'Wedding Loans'
}
print(listing_num_to_string[9])
df_loan_data_cleaned['ListingCategory'] = df_loan_data_cleaned['ListingCategory (numeric)'].apply(lambda x: listing_num_to_string[x]) 
df_loan_data_cleaned.ListingCategory = df_loan_data_cleaned.ListingCategory.astype('category')
df_loan_data_cleaned.drop(columns=['ListingCategory (numeric)'], inplace=True)
df_loan_data_cleaned.head()

Boat

,LoanStatus,BorrowerRate,Occupation,IsBorrowerHomeowner,DelinquenciesLast7Years,StatedMonthlyIncome,LoanOriginalAmount,LoanOriginationDate,Recommendations,CreditScoreRangeAvg,ListingCategory
0,Completed,0.1580,Other,True,4,3083.333333,9425,2007-09-12 00:00:00,0,649.5,Not Available
1,Current,0.0920,Professional,False,0,6125.000000,10000,2014-03-03 00:00:00,0,689.5,Home Improvement
2,Completed,0.2750,Other,False,0,2083.333333,3001,2007-01-17 00:00:00,0,489.5,Not Available
3,Current,0.0974,Skilled Labor,True,14,2875.000000,10000,2012-11-01 00:00:00,0,809.5,Motorcycle
4,Current,0.2085,Executive,True,0,9583.333333,15000,2013-09-20 00:00:00,0,689.5,Home Improvement

### Test

In [31]:
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110345 entries, 0 to 113936
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   LoanStatus               110345 non-null  category
 1   BorrowerRate             110345 non-null  float64
 2   Occupation               110345 non-null  category
 3   IsBorrowerHomeowner      110345 non-null  bool
 4   DelinquenciesLast7Years  110345 non-null  int64
 5   StatedMonthlyIncome      110345 non-null  float64
 6   LoanOriginalAmount       110345 non-null  int64
 7   LoanOriginationDate      110345 non-null  object
 8   Recommendations          110345 non-null  int64
 9   CreditScoreRangeAvg      110345 non-null  float64
 10  ListingCategory          110345 non-null  category
dtypes: bool(1), category(3), float64(3), int64(3), object(1)
memory usage: 7.2+ MB

In [32]:
df_loan_data_cleaned.ListingCategory

0              Not Available
1           Home Improvement
2              Not Available
3                 Motorcycle
4           Home Improvement
                 ...
113932    Debt Consolidation
113933                 Other
113934    Debt Consolidation
113935      Home Improvement
113936    Debt Consolidation
Name: ListingCategory, Length: 110345, dtype: category
Categories (21, object): ['Auto', 'Baby Adoption', 'Boat', 'Business', ..., 'Student Use', 'Taxes', 'Vacation', 'Wedding Loans']

## LoanOriginationDate
### Define
Transform the loan origination date variable from object to date time.

### Code

In [33]:
df_loan_data_cleaned.LoanOriginationDate = pd.to_datetime(df_loan_data_cleaned.LoanOriginationDate)

### Test

In [34]:
df_loan_data_cleaned.LoanOriginationDate

0        2007-09-12
1        2014-03-03
2        2007-01-17
3        2012-11-01
4        2013-09-20
            ...
113932   2013-04-22
113933   2011-11-07
113934   2013-12-23
113935   2011-11-21
113936   2014-01-21
Name: LoanOriginationDate, Length: 110345, dtype: datetime64[ns]

In [35]:
df_loan_data_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 110345 entries, 0 to 113936
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   LoanStatus               110345 non-null  category
 1   BorrowerRate             110345 non-null  float64
 2   Occupation               110345 non-null  category
 3   IsBorrowerHomeowner      110345 non-null  bool
 4   DelinquenciesLast7Years  110345 non-null  int64
 5   StatedMonthlyIncome      110345 non-null  float64
 6   LoanOriginalAmount       110345 non-null  int64
 7   LoanOriginationDate      110345 non-null  datetime64[ns]
 8   Recommendations          110345 non-null  int64
 9   CreditScoreRangeAvg      110345 non-null  float64
 10  ListingCategory          110345 non-null  category
dtypes: bool(1), category(3), datetime64[ns](1), float64(3), int64(3)
memory usage: 7.2 MB

All the variables are now in the proper format.

# Data set saving
In order to use this cleaned data set in the next notebook, we save it into a csv file.

In [36]:
df_loan_data_cleaned.to_csv('prosperLoanDataCleaned.csv', index=False)